language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.6
  - 2.3.1
  - 2.4.1
  - rbx-2
gemfile:
  - GemfileTravis
env:
  - SELENIUM_SERVER_URL=http://ondemand.saucelabs.com/wd/hub
matrix:
  allow_failures:
    - rvm: rbx-2

sudo: false

branches:
  only:
    - master
    - development

before_install:
  - "gem install builder"
  - "BUILD_ONLY=true rake clean build"
  - "cd pkg; mkdir gems; mv ./*.gem ./gems; gem generate_index; cd .."
script:
  - bundle exec rake
