'use strict'
function createRSpecTestFileString({key, skip, output, meta}) {
  return `# Generated by Ruby template
${output.hooks.deps.join('\n')}

RSpec.describe 'Coverage Tests' do
  ${output.hooks.vars.join('\n  ')}
  before :example do
    ${output.hooks.beforeEach.join('\n    ')}
  end
  after :example do
    ${output.hooks.afterEach.join('\n    ')}
  end
  ${skip ? 'skip' : 'it'} '${key}' do
    ${output.commands.join('\n    ')}
  end
end
`
}

module.exports = createRSpecTestFileString
