name: Ruby

on:
  workflow_dispatch:
  push:


permissions:
  contents: read

jobs:
  dist-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Build gems
        env:
          BUILD_ONLY: true
        run: |
            gem install builder
            rake clobber clean build
            cd pkg; mkdir gems; mv ./*.gem ./gems; gem generate_index; cd ..
      - name: Store gems
        uses: actions/upload-artifact@v3
        with:
          name: gems
          if-no-files-found: error
          path: "./pkg/*"
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate platform tests
        run: |
          npm install
          npm run generate:platform
      - name: Store platform tests
        uses: actions/upload-artifact@v3
        with:
          name: platform-tests
          if-no-files-found: error
          path: "./coverage_tests/spec/**/*"
      - name: Generate generic tests
        run: |
          npm install
          npm run generate
      - name: Store generic tests
        uses: actions/upload-artifact@v3
        with:
          name: generic-tests
          if-no-files-found: error
          path: "./coverage_tests/spec/**/*"



  platform-test:
    needs: dist-build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        ruby-version: ['2.6', '2.7', '3.0', '3.1']
    runs-on: ${{ matrix.os }}
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
#          bundler-cache: true
      - name: Load gems
        uses: actions/download-artifact@v3
        with:
          name: gems
          path: "./pkg/"
#      - name: Check gems
#        run: |
#          ls pkg
#          ls pkg\gems
      - name: Load tests
        uses: actions/download-artifact@v3
        with:
          name: platform-tests
          path: "./coverage_tests/spec/"
#      - name: Check tests
#        run: |
#          ls coverage_tests
#          ls coverage_tests/spec
#          ls coverage_tests/spec/coverage/generic
      - name: Run tests
        env:
          BUNDLE_GEMFILE: ${{ github.workspace }}/GemfileGithub
        run: |
            bundle install
            bundle exec rake github:platform_test
          
  unit-test:
    needs: dist-build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ruby-version: ['2.6', '2.7', '3.0', '3.1']
    runs-on: ${{ matrix.os }}
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Load gems
        uses: actions/download-artifact@v3
        with:
          name: gems
          path: "./pkg/"
      - name: Run tests
        env:
          BUNDLE_GEMFILE: ${{ github.workspace }}/GemfileGithub
        run: |
          bundle install
          bundle exec rake github:unit_tests

  visual-test:
    needs: dist-build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ruby-version: ['2.6', '2.7', '3.0', '3.1']
    runs-on: ${{ matrix.os }}
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Load gems
        uses: actions/download-artifact@v3
        with:
          name: gems
          path: "./pkg/"
      - name: Run visual tests
        env:
          BUNDLE_GEMFILE: ${{ github.workspace }}/GemfileGithub
        run: |
          bundle install
          bundle exec rake github:vg_tests

  appium-test:
    needs: dist-build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ruby-version: ['2.6', '2.7', '3.0', '3.1']
    runs-on: ${{ matrix.os }}
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Load gems
        uses: actions/download-artifact@v3
        with:
          name: gems
          path: "./pkg/"
      - name: Run Appium tests
        env:
          BUNDLE_GEMFILE: ${{ github.workspace }}/GemfileGithub
        run: |
          bundle install
          bundle exec rake github:appium_tests
